### ISSUE TITLE
Creating product through API generates internal exception that has no meaning

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1053]
### Expected behavior

Should tell which property was not populated.

### Actual behavior

When calling CreateProduct API error is thrown:

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.LoadDependencies(CatalogProduct[] products, Boolean processVariations)
   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.ValidateProductProperties(CatalogProduct[] products)
   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.SaveChanges(CatalogProduct[] products, Boolean disableValidation)
   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.Create(CatalogProduct item)

### Steps to reproduce
Call product create using:

```
var product = new CatalogProduct()
{
CatalogId = "electronics",
Id = "sample",
Name = "sample"
};
_itemService.Create(product);
```

**Comment by Woland2k** [comment]
Now new error came up:

{"message":"An error has occurred.","exceptionMessage":"Object reference not set to an instance of an object.","exceptionType":"System.NullReferenceException","stackTrace":"   at VirtoCommerce.CatalogModule.Data.Services.Validation.ProductValidator.<>c.<.ctor>b__1_0(String x) in c:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\Validation\\ProductValidator.cs:line 20\r\n   at FluentValidation.Validators.PredicateValidator.IsValid(PropertyValidatorContext context)\r\n   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context)\r\n   at FluentValidation.Internal.PropertyRule.<Validate>d__60.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at FluentValidation.Results.ValidationResult..ctor(IEnumerable`1 failures)\r\n   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context)\r\n   at FluentValidation.DefaultValidatorExtensions.ValidateAndThrow[T](IValidator`1 validator, T instance, String ruleSet)\r\n   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.ValidateProducts(CatalogProduct[] products) in c:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\ItemServiceImpl.cs:line 358\r\n   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.SaveChanges(CatalogProduct[] products, Boolean disableValidation) in c:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\ItemServiceImpl.cs:line 159\r\n   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.Create(CatalogProduct[] items) in c:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\ItemServiceImpl.cs:line 129\r\n   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.Create(CatalogProduct item) in c:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\ItemServiceImpl.cs:line 134\r\n

**Comment by Woland2k** [comment]
another error:

{"message":"An error has occurred.","exceptionMessage":"Value cannot be null.\r\nParameter name: source","exceptionType":"System.ArgumentNullException","stackTrace":"   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.ApplyInheritanceRules(CatalogProduct[] products, Boolean processVariations) in C:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\ItemServiceImpl.cs:line 294\r\n   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.ValidateProducts(CatalogProduct[] products) in C:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\ItemServiceImpl.cs:line 362\r\n   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.SaveChanges(CatalogProduct[] products, Boolean disableValidation) in C:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\ItemServiceImpl.cs:line 159\r\n   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.Create(CatalogProduct[] items) in C:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\ItemServiceImpl.cs:line 129\r\n   at VirtoCommerce.CatalogModule.Data.Services.ItemServiceImpl.Create(CatalogProduct item) in C:\\Projects\\GitHub\\vc-module-catalog\\VirtoCommerce.CatalogModule.Data\\Services\\ItemServiceImpl.cs:line 134
