### ISSUE TITLE
Uploading theme through backened gives 500 error

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1826]
**Describe the bug**
When dropping the zip to upload the file, the following error happens, directory does exist and is created, however FileStorage is trying to OpenWrite a directory instead of the actual file.

System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=Could not find a part of the path 'C:\Projects\GitHub\VirtoCommerce\vc-platform\src\VirtoCommerce.Platform.Web\wwwroot\cms-content\Themes\Electronics\odt-theme-0.1.13\'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode)
   at VirtoCommerce.Platform.Assets.FileSystem.FileSystemBlobProvider.OpenWrite(String blobUrl) in C:\Projects\GitHub\VirtoCommerce\vc-platform\src\VirtoCommerce.Platform.Assets.FileSystem\FileSystemBlobProvider.cs:line 94
   at VirtoCommerce.ContentModule.Web.Controllers.Api.ContentController.<Unpack>d__10.MoveNext()

**Steps to reproduce**
1. Open upload theme.
2. Download latest ODT theme.
3. Drag and drop ODT zip.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1566470/78830635-21ac7c80-799d-11ea-9d81-643d2d1eb021.png)

**Version info (please complete the following information):**
 - Browser version: 3 rc4
 - Platform version:

**Comment by Woland2k** [comment]
This is because odt theme is not correctly packaged, it should have nothing in the root directory of the zip except one directory called "odt"

**Comment by Woland2k** [comment]
Issue moved to [VirtoCommerce/vc-module-content #48](https://github.com/VirtoCommerce/vc-module-content/issues/48) via [**ZenHub**](https://www.zenhub.com/)
