### ISSUE TITLE
New fresh platform install generates the exception TenantIdentity.Empty field not found

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1835]
**Describe the bug**
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at VirtoCommerce.Platform.Core.Common.AbstractTypeFactory`1.TryCreateInstance(String typeName) in C:\Projects\GitHub\VirtoCommerce\vc-platform\src\VirtoCommerce.Platform.Core\Domain\AbstractTypeFactory.cs:line 113
   at VirtoCommerce.NotificationsModule.Data.Services.NotificationSearchService.<>c.<GetTransientNotifications>b__8_1(TypeInfo`1 x)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at VirtoCommerce.NotificationsModule.Data.Services.NotificationSearchService.<>c.<GetTransientNotifications>b__8_0(MemoryCacheEntryOptions cacheEntry)
   at VirtoCommerce.Platform.Core.Caching.MemoryCacheExtensions.GetOrCreateExclusive[TItem](IMemoryCache cache, String key, Func`2 factory, Boolean cacheNullValue) in C:\Projects\GitHub\VirtoCommerce\vc-platform\src\VirtoCommerce.Platform.Core\Caching\MemoryCacheExtensions.cs:line 41
   at VirtoCommerce.NotificationsModule.Data.Services.NotificationSearchService.GetTransientNotifications()
   at VirtoCommerce.NotificationsModule.Data.Services.NotificationSearchService.GetNotificationType(String notificationType)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)

Inner Exception 1:
MissingFieldException: Field not found: 'VirtoCommerce.Platform.Core.Common.TenantIdentity.Empty'.
```

**Steps to reproduce**
1. Remove old modules and database.
2. Start up admin and install all default modules.
3. Restart and open in platform debug mode.

PS: this is the type of error that CI should catch, why wasn't basic setup test not running?

Probably due to this checkin: https://github.com/VirtoCommerce/vc-platform/commit/99f673668c65e1d543e6a69673072902a8c2af86

**Comment by lnetrebskii** [comment]
Fixed in [in 3.0.0-rc.5](https://github.com/VirtoCommerce/vc-platform/releases/tag/3.0.0-rc.5.248)
