### ISSUE TITLE
Can't run latest RC5? platform

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1837]
**Describe the bug**
```
fail: VirtoCommerce.Platform.Modules.ModuleInitializer[0]
      VirtoCommerce.Platform.Core.Modularity.Exceptions.ModuleInitializeException: An exception occurred while initializing module VirtoCommerce.Core.
       ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
      Could not load file or assembly 'VirtoCommerce.Platform.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      Could not load file or assembly 'VirtoCommerce.Platform.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      Could not load file or assembly 'VirtoCommerce.Platform.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      Could not load file or assembly 'VirtoCommerce.Platform.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      Could not load file or assembly 'VirtoCommerce.Platform.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
         at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
         at System.Reflection.RuntimeModule.GetTypes()
         at System.Reflection.Assembly.GetTypes()
         at VirtoCommerce.Platform.Modules.ModuleInitializer.CreateModule(ModuleInfo moduleInfo) in C:\Projects\GitHub\VirtoCommerce\vc-platform\src\VirtoCommerce.Platform.Modules\ModuleInitializer.cs:line 126
         at VirtoCommerce.Platform.Modules.ModuleInitializer.Initialize(ModuleInfo moduleInfo) in C:\Projects\GitHub\VirtoCommerce\vc-platform\src\VirtoCommerce.Platform.Modules\ModuleInitializer.cs:line 44
      System.IO.FileNotFoundException: Could not load file or assembly 'VirtoCommerce.Platform.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'VirtoCommerce.Platform.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null'
      
```
**Steps to reproduce**
1. Download latest platform code from release/3.0.0
2. Go through process of installing modules.
3. Restart and open the admin.

**Comment by akak1977** [comment]
This solved. Just try again, please.
