### ISSUE TITLE
Not able to get login window in chrome running application in visual studio 2019

### ISSUE THREAD

**Issue by mbangali** [VirtoCommerce/vc-platform#2367]
I am getting following error while launching application on visual studio 2019. I am not able to view login window and i am getting following error in console application.

I have used following command  

npm install node-sass

main.sass:1 Uncaught Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.12.0
    at module.exports (D:\vc\src\VirtoCommerce.Platform.Web\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (D:\vc\src\VirtoCommerce.Platform.Web\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (D:\vc\src\VirtoCommerce.Platform.Web\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (D:\vc\src\VirtoCommerce.Platform.Web\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.sassLoader (D:\vc\src\VirtoCommerce.Platform.Web\node_modules\sass-loader\lib\loader.js:46:72)
    at D:\vc\src\VirtoCommerce.Platform.Web\node_modules\webpack\lib\NormalModule.js:302:20
    at D:\vc\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\vc\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at runSyncOrAsync (D:\vc\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (D:\vc\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\vc\src\VirtoCommerce.Platform.Web\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\vc\src\VirtoCommerce.Platform.Web\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at D:\vc\src\VirtoCommerce.Platform.Web\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9
    at D:\vc\src\VirtoCommerce.Platform.Web\node_modules\enhanced-resolve\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
    at eval (webpack:///./wwwroot/css/themes/main/sass/main.sass?:1:7)
    at Object../wwwroot/css/themes/main/sass/main.sass (http://localhost:10645/dist/vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:4319:1)
    at __webpack_require__ (http://localhost:10645/dist/vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:20:30)
    at eval (webpack:///multi_./wwwroot/src/js/vendor.js_./wwwroot/css/themes/main/sass/main.sass?:2:18)
    at Object.0 (http://localhost:10645/dist/vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:4365:1)
    at __webpack_require__ (http://localhost:10645/dist/vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:20:30)
    at http://localhost:10645/dist/vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:84:18
    at http://localhost:10645/dist/vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:87:10
eval @ main.sass:1
./wwwroot/css/themes/main/sass/main.sass @ vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:4319
__webpack_require__ @ vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:20
eval @ main.sass:2
0 @ vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:4365
__webpack_require__ @ vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:20
(anonymous) @ vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:84
(anonymous) @ vendor.js?v=sgrhScnTkWE72OffatD_k-gmoKW4s6uz1poIv1RkWOw:87
:10645/api/platform/security/currentuser:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)

-
![login](https://user-images.githubusercontent.com/28632550/132129863-1ce83717-41e2-4171-b0d5-2ed46bb0251c.png)
![login](https://user-images.githubusercontent.com/28632550/132129923-6efcccb2-8076-4add-b808-d40d4a48ba05.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7700 has been created

**Comment by OlegoO** [comment]
@mbangali 
As a workaround, I recommend to use the runtime version of the platform, by default it's not necessary https://virtocommerce.com/docs/latest/vc-quickstart/


Did you test these solutions?
https://medium.com/@proustibat/how-to-fix-error-node-sass-does-not-yet-support-your-current-environment-os-x-64-bit-with-c1b3298e4af0
https://stackoverflow.com/questions/37415134/error-node-sass-does-not-yet-support-your-current-environment-windows-64-bit-w

**Comment by mbangali** [comment]
Both the solutions did not worked for me.

https://medium.com/@proustibat/how-to-fix-error-node-sass-does-not-yet-support-your-current-environment-os-x-64-bit-with-c1b3298e4af0
https://stackoverflow.com/questions/37415134/error-node-sass-does-not-yet-support-your-current-environment-windows-64-bit-w

**Comment by OlegoO** [comment]
I recommend submitting the issue to node-sass https://github.com/sass/node-sass/

Node Sass could not resolve - does not yet support your current environment: Windows 64-bit with Unsupported runtime (83).
May be something wrong with NodeJS, Python, etc.

And use the runtime version of Virto Commerce.
