### ISSUE TITLE
GraphQL query cart return error

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-platform#2473]
**Describe the bug**
Can't use the vue-starter-theme in the storefront project.

**Steps to reproduce**
1. vc.platform is ok
2. clone the latest storefront project and config then run.
3. Open storefront url http://localhost:2083/xapi/graphql with chrome.The screen is empty.
4. open the chrome console ,see some errors.

**Expected behavior**
I want to test the vue-starter-theme successful.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/5348170/156516454-d60d7a15-fc03-4be6-8956-51a8d79bd092.png)

**Version info (please complete the following information):**
 - Browser version:Chrome 98.0.4758.102
 - Platform version: 3.204.0

**Additional context (optional)**

http://localhost:2083/xapi/graphql

request
```
{"operationName":"getMyCart","variables":{"storeId":"B2B-store","userId":"dcdb108a-d731-46b8-ad58-69d976006c31","currencyCode":"USD","cultureName":"en-US"},"query":"query getMyCart($storeId: String!, $userId: String!, $currencyCode: String!, $cultureName: String) {\n  cart(\n    storeId: $storeId\n    userId: $userId\n    currencyCode: $currencyCode\n    cultureName: $cultureName\n  ) {\n    id\n    name\n    comment\n    purchaseOrderNumber\n    coupons {\n      code\n    }\n    itemsCount\n    itemsQuantity\n    shipments {\n      id\n      shipmentMethodCode\n      shipmentMethodOption\n      deliveryAddress {\n        ...cartAddressFields\n      }\n      price {\n        ...moneyFields\n      }\n    }\n    discounts {\n      promotionId\n      description\n      amount\n      coupon\n    }\n    payments {\n      id\n      paymentGatewayCode\n      billingAddress {\n        ...cartAddressFields\n      }\n    }\n    addresses {\n      ...cartAddressFields\n    }\n    items {\n      ...lineItemFields\n    }\n    currency {\n      ...currencyFields\n    }\n    total {\n      ...moneyFields\n    }\n    discountTotal {\n      ...moneyFields\n    }\n    subTotal {\n      ...moneyFields\n    }\n    shippingTotal {\n      ...moneyFields\n    }\n    shippingPrice {\n      ...moneyFields\n    }\n    taxTotal {\n      ...moneyFields\n    }\n    extendedPriceTotal {\n      ...moneyFields\n    }\n    extendedPriceTotalWithTax {\n      ...moneyFields\n    }\n    validationErrors(ruleSet: \"items\") {\n      errorCode\n      errorMessage\n      errorParameters {\n        key\n        value\n      }\n      objectId\n    }\n    availablePaymentMethods {\n      code\n      logoUrl\n      price {\n        ...moneyFields\n      }\n    }\n    availableShippingMethods {\n      id\n      code\n      logoUrl\n      optionName\n      optionDescription\n      price {\n        ...moneyFields\n      }\n    }\n    gifts {\n      id\n      imageUrl\n      name\n      lineItemId\n    }\n    availableGifts {\n      id\n      imageUrl\n      name\n      lineItemId\n    }\n  }\n}\n\nfragment cartAddressFields on CartAddressType {\n  id\n  name\n  organization\n  firstName\n  lastName\n  line1\n  line2\n  city\n  countryCode\n  countryName\n  regionId\n  regionName\n  postalCode\n  zip\n  phone\n  email\n  addressType\n}\n\nfragment lineItemFields on LineItemType {\n  id\n  imageUrl\n  inStockQuantity\n  isGift\n  isReadOnly\n  isReccuring\n  isValid\n  name\n  productId\n  product {\n    brandName\n    slug\n    masterVariation {\n      id\n    }\n    minQuantity\n    maxQuantity\n    variations {\n      id\n      minQuantity\n      maxQuantity\n    }\n  }\n  quantity\n  sku\n  thumbnailImageUrl\n  validationErrors {\n    errorCode\n    errorMessage\n    errorParameters {\n      key\n      value\n    }\n  }\n  extendedPrice {\n    ...moneyFields\n  }\n  listPrice {\n    ...moneyFields\n  }\n  taxTotal {\n    ...moneyFields\n  }\n}\n\nfragment moneyFields on MoneyType {\n  amount\n  decimalDigits\n  formattedAmount\n  formattedAmountWithoutCurrency\n  formattedAmountWithoutPoint\n  formattedAmountWithoutPointAndCurrency\n  currency {\n    ...currencyFields\n  }\n}\n\nfragment currencyFields on CurrencyType {\n  code\n  customFormatting\n  exchangeRate\n  symbol\n}\n"}
```

response
```
{"errors":[{"message":"GraphQL.Execution.UnhandledError: Error trying to resolve field 'cart'.\r\n ---> System.ArgumentNullException: Value cannot be null. (Parameter 'principal')\r\n   at System.Security.Claims.PrincipalExtensions.FindFirstValue(ClaimsPrincipal principal, String claimType)\r\n   at VirtoCommerce.Platform.Security.Authorization.PermissionAuthorizationHandlerBase`1.HandleRequirementAsync(AuthorizationHandlerContext context, TRequirement requirement) in E:\\VirtoCommerce\\5.Source\\vc-platform-3.204.0\\src\\VirtoCommerce.Platform.Security\\Authorization\\PermissionAuthorizationHandlerBase.cs:line 15\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)\r\n   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)\r\n   at VirtoCommerce.XPurchase.Schemas.PurchaseSchema.CheckAccessToCartAsync(IResolveFieldContext context, ShoppingCart cart) in /home/runner/work/vc-module-experience-api/vc-module-experience-api/src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs:line 1230\r\n   at VirtoCommerce.XPurchase.Schemas.PurchaseSchema.<Build>b__6_37(IResolveFieldContext context) in /home/runner/work/vc-module-experience-api/vc-module-experience-api/src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs:line 85\r\n   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 429\r\n   --- End of inner exception stack trace ---","locations":[{"line":2,"column":3}],"path":["cart"],"extensions":{"code":"ARGUMENT_NULL","codes":["ARGUMENT_NULL"]}}],"data":{"cart":null}}
```

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7962 has been created

**Comment by Flanker72** [comment]
Hello, @six006 !
It seems that you have some outdated modules, because similar error was already fixed [here](https://github.com/VirtoCommerce/vc-module-experience-api/pull/280).

Please, double check the installed versions of additional Platform modules:
* Experience API version at least [3.203.0](https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.203.0-pr-283.zip)
* Profile Experience API version at least [3.201.0](https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.201.0-pr-8.zip)

**Comment by six006** [comment]
thanks @Flanker72 ! After update the Experience API module to [3.203.0],return another errors
```
ArgumentNullException: Value cannot be null. (Parameter 'source')
System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
System.Linq.Enumerable.Select<TSource, TResult>(IEnumerable<TSource> source, Func<TSource, TResult> selector)
VirtoCommerce.Storefront.Domain.StoreService.<GetAllStoresAsync>b__5_0(MemoryCacheEntryOptions cacheEntry) in StoreService.cs
+
                return await Task.WhenAll(storeDtos.Select(x => ConvertStoreAndLoadDependeciesAsync(x)));
VirtoCommerce.Storefront.Model.Common.Caching.MemoryCacheExtensions.GetOrCreateExclusiveAsync<TItem>(IMemoryCache cache, string key, Func<MemoryCacheEntryOptions, Task<TItem>> factory, bool cacheNullValue) in MemoryCacheExtensions.cs
+
                        result = await factory(options);
VirtoCommerce.Storefront.Domain.StoreService.GetAllStoresAsync() in StoreService.cs
+
            return await _memoryCache.GetOrCreateExclusiveAsync(cacheKey, async (cacheEntry) =>
VirtoCommerce.Storefront.Domain.StoreWorkContextBuilderExtensions.WithStoresAsync(IWorkContextBuilder builder, string defaultStoreId) in StoreWorkContextBuilderExtensions.cs
+
            var stores = await storeService.GetAllStoresAsync();
VirtoCommerce.Storefront.Middleware.WorkContextBuildMiddleware.Invoke(HttpContext context) in WorkContextBuildMiddleware.cs
+
            await builder.WithStoresAsync(_options.DefaultStore);
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at VirtoCommerce.Storefront.Domain.StoreService.<GetAllStoresAsync>b__5_0(MemoryCacheEntryOptions cacheEntry) in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront\Domain\Stores\StoreService.cs:line 44
   at VirtoCommerce.Storefront.Model.Common.Caching.MemoryCacheExtensions.GetOrCreateExclusiveAsync[TItem](IMemoryCache cache, String key, Func`2 factory, Boolean cacheNullValue) in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront.Model\Common\Caching\MemoryCacheExtensions.cs:line 21
   at VirtoCommerce.Storefront.Domain.StoreService.GetAllStoresAsync() in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront\Domain\Stores\StoreService.cs:line 38
   at VirtoCommerce.Storefront.Domain.StoreWorkContextBuilderExtensions.WithStoresAsync(IWorkContextBuilder builder, String defaultStoreId) in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront\Domain\Stores\StoreWorkContextBuilderExtensions.cs:line 54
   at VirtoCommerce.Storefront.Middleware.WorkContextBuildMiddleware.Invoke(HttpContext context) in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront\Middleware\WorkContextBuildMiddleware.cs:line 52
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
![image](https://user-images.githubusercontent.com/5348170/156616040-760bd458-8b92-4b8c-8ad7-0ab2fa90e9be.png)

**Comment by six006** [comment]
I close this issue and create new issue about this error.
