### ISSUE TITLE
Weird service collection self-registration

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-platform#2795]
Hi, is there any reason the platform registers the DI service collection in itself? This feels very weird...

https://github.com/VirtoCommerce/vc-platform/blob/ddce0c966f011c9e33dfb2f2a6a85bf789b4ab1f/src/VirtoCommerce.Platform.Web/Extensions/ServiceCollectionExtensions.cs#L18

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8582 has been created

**Comment by OlegoO** [comment]
@j-mok Good quetion, the code was added 5 years ago, I will review with the team and maybe find some reason.

**Comment by OlegoO** [comment]
This code is required to resolve IServiceCollection for ModuleInitializer class and then pass to modules. Without this line, DI throws exception. Maybe code can be improved but let's keep it as is.

```log
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.DependencyInjection.IServiceCollection' while attempting to activate 'VirtoCommerce.Platform.Modules.ModuleInitializer'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
...   
at VirtoCommerce.Platform.Modules.ServiceCollectionExtensions.AddModules(IServiceCollection services, IMvcBuilder mvcBuilder, Action`1 setupAction) in C:\Projects\git\VirtoCommerce\vc-platform\src\VirtoCommerce.Platform.Web\Extensions\ServiceCollectionExtensions.cs:line 33
...
```
