### ISSUE TITLE
VirtoCommerce Import CSV does not work without file type metadata.

### ISSUE THREAD

**Issue by Davidaredding** [VirtoCommerce/vc-platform#392]
As mentioned here (http://help.virtocommerce.com/support/discussions/topics/4000328329?page=1) 

this code in catalog-CSV-import-wizard.js causes issues on machines without the 'application/vnd.ms-excel' type metadata.

```
    'uploader.filters.push({
        name: 'csvFilter',
        fn: function (i /*{File|FileLikeObject}*/, options) {
            var type = '|' + i.type.slice(i.type.lastIndexOf('/') + 1) + '|';
            return '|csv|vnd.ms-excel|'.indexOf(type) !== -1;
        }
    });'
```

I recommend updating the uploader to filter the initial file dialog box by file name extensions or provide feedback when csv is not found in the type metadata.

**Comment by Davidaredding** [comment]
Perhaps just amending the last line to read
return '|csv|vnd.ms-excel|'*.toLowerCase()*.indexOf(type) !== -1;

**Comment by tatarincev** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
 at VirtoCommerce.CatalogModule.Web.ExportImport.CsvCatalogImporter.SaveProduct(Catalog catalog, FulfillmentCenter defaultFulfillmentCenter, CsvProduct csvProduct) in C:\[...]\Projects\vc-community-master\PLATFORM\Modules\Catalog\VirtoCommerce.CatalogModule.Web\ExportImport\CsvCatalogImporter.cs:line 296
 at VirtoCommerce.CatalogModule.Web.ExportImport.CsvCatalogImporter.<>c__DisplayClass15_0.<SaveProducts>b__2(CsvProduct csvProduct) in C:\[...]\PLATFORM\Modules\Catalog\VirtoCommerce.CatalogModule.Web\ExportImport\CsvCatalogImporter.cs:line 163

I did get this error either by import the csv generated by virto commerce, and also by importing the simplest csv:

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
