### ISSUE TITLE
Deployment to Azure doesn't work

### ISSUE THREAD

**Issue by amironoff** [VirtoCommerce/vc-platform#580]
Hello,

The Azure deployment routine described [here](http://docs.virtocommerce.com/display/vc2devguide/Deploy+from+GitHub+to+Microsoft+Cloud+Azure) deploys VirtoCommerce platorm successfully.

However, the website doesn't display the login form. Judging from Chrome F12 tools, seems it's a routing/configuration issue - ($Platform) is not resolved:

![image](https://cloud.githubusercontent.com/assets/10373681/17375740/f9b53b6e-59ba-11e6-8033-e8c2654b602a.png)

Any ideas what's going on here?

**Comment by artem-dudarev** [comment]
Cannot reproduce.
I've deployed master and dev branches and both show the login form.

**Comment by amironoff** [comment]
I just deployed master branch one more time. I confirm that the issue still exists. Tested in latest Chrome and IE Edge

**Comment by amironoff** [comment]
Here's the setup:

![image](https://cloud.githubusercontent.com/assets/10373681/17411036/1abfcd3c-5a7f-11e6-8578-40ab22578e26.png)

**Comment by amironoff** [comment]
and the result...

![image](https://cloud.githubusercontent.com/assets/10373681/17411105/670c674a-5a7f-11e6-9765-83531914d4d2.png)

**Comment by Woland2k** [comment]
Can you send us url for the site? Also can you make sure it is not simply cached?

**Comment by amironoff** [comment]
Interestingly, after I downgrade the App Service Plan to 'Free', the issue stops and the login form appears...

**Comment by amironoff** [comment]
@Woland2k Did a 3d deploy. Same result, blank page - https://vc-platformd908.azurewebsites.net/

**Comment by amironoff** [comment]
@Woland2k if you're referring to browser cache, I did a full page reload (CTRL+F5)...

**Comment by Woland2k** [comment]
Thanks for the link, I can see now that login template is not loading, should be enough for our developer to troubleshoot now.

**Comment by artem-dudarev** [comment]
Short answer:
Restart the Azure web app

Long answer:
Looks like one more bug in Azure.

I selected Site Location 'North Europe', Sku 'Standard' and Worker Size 'Medium' and deployment has failed with the following error:

```
Deployment Error
Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__6d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__3b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__6.MoveNext().
```


Then I manually configured Deployment source in the Azure portal and get your error with login.tpl.html

The error has gone when I clicked the Restart  button in the Azure web app details.

**Comment by amironoff** [comment]
ah, the good old restart button to the rescue yet again :) Thanks @artem-dudarev
